openapi: 3.0.0
info:
  title: mega_back endpoints documentation
  description: "routes, requests and responses of our server"
  version: "1.1"
servers:
- url: https://virtserver.swaggerhub.com/VINIDSB580/mega_back/1.1
  description: SwaggerHub API Auto Mocking
- url: http://localhost:3001
paths:
  /adicionarProduto:
    post: #testando integração com o swaggerhub
      summary: Saves a product on database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/adicionarProduto_body'
        required: true
      responses:
        "201":
          description: product has been added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: "some invalid data, invalid sintax etc"
        "500":
          description: server internal error
  /listarMedicamentos:
    get:
      summary: Returs a list of medicines
      responses:
        "200":
          description: products list sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "500":
          description: server internal error
  /cadastrarCli:
    post:
      summary: Validate data and register a new client account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cadastrarCli_body'
        required: true
      responses:
        "201":
          description: client registration created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: "some data may be invalid, wrong sintax, characters, size etc"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "401":
          description: unauthorized credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "500":
          description: server internal error
  /cadastrarAdm:
    post:
      summary: Validate data and register a manager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cadastrarAdm_body'
        required: true
      responses:
        "201":
          description: manager registration created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: "some data may be invalid, wrong sintax, characters, size etc"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "401":
          description: unauthorized credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "500":
          description: server internal error
  /fazerLogin:
    post:
      summary: Checks the credentials and respond with user data if success
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/fazerLogin_body'
        required: true
      responses:
        "202":
          description: login accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "401":
          description: incorrect email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: "data validation error, not an email, not allowed characters,\
            \ etc"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "500":
          description: server internal error
components:
  schemas:
    adicionarProduto_body:
      type: object
      properties:
        medName:
          type: string
        medDescription:
          type: string
        medUnitPrice:
          type: number
        amountOnStock:
          type: integer
        managerWhoAdded:
          type: string
        needRecipe:
          type: boolean
    inline_response_201:
      type: object
      properties:
        message:
          type: string
    inline_response_200:
      type: object
      properties:
        message:
          type: string
        medicineList:
          type: array
          items:
            type: object
            properties:
              medName:
                type: string
              medDescription:
                type: string
              medUnitPrice:
                type: number
              needRecipe:
                type: boolean
    cadastrarCli_body:
      type: object
      properties:
        name:
          type: string
        cpf:
          type: string
        email:
          type: string
        password:
          type: string
        passwordRepeat:
          type: string
        rg:
          type: integer
        address:
          type: string
        phone:
          type: integer
    inline_response_201_1:
      type: object
      properties:
        message:
          type: string
        email:
          type: string
        name:
          type: string
    cadastrarAdm_body:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        passwordRepeat:
          type: string
    fazerLogin_body:
      type: object
      properties:
        email:
          type: string
        password:
          type: string