openapi: 3.0.0
info:
  version: '1.0'
  title: mega_back endpoints documentation
  description: routes, requests and responses of our server
paths:
  /adicionarProduto:
    post:
      summary: Saves a product on database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                medName:
                  type: string
                medDescription:
                  type: string
                medUnitPrice:
                  type: number
                amountOnStock:
                  type: integer
                managerWhoAdded:
                  type: string
                needRecipe:
                  type: boolean
      responses:
        '201':
          description: product has been added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: some invalid data, invalid sintax etc
        '500':
          description: server internal error
  
  /listarMedicamentos:
    get:
      summary: Returs a list of medicines
      responses:
        '200':
          description: products list sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  medicineList:
                    type: array
                    items:
                      type: object
                      properties:
                        medName:
                          type: string
                        medDescription:
                          type: string
                        medUnitPrice:
                          type: number
                        needRecipe:
                          type: boolean
        '500':
          description: server internal error
          
  /cadastrarCli:
    post:
      summary: Validate data and register a new client account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cpf:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordRepeat:
                  type: string
                rg:
                  type: integer
                address:
                  type: string
                phone:
                  type: integer
      responses:
        '201':
          description: client registration created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '400':
          description: some data may be invalid, wrong sintax, characters, size etc
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '401':
          description: unauthorized credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '500':
          description: server internal error
        
  /cadastrarAdm:
    post:
      summary: Validate data and register a manager
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordRepeat:
                  type: string
      responses:
        '201':
          description: manager registration created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '400':
          description: some data may be invalid, wrong sintax, characters, size etc
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '401':
          description: unauthorized credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '500':
          description: server internal error
  
  /fazerLogin:
    post:
      summary: Checks the credentials and respond with user data if success
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '202':
          description: login accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '401':
          description: incorrect email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '400':
          description: data validation error, not an email, not allowed characters, etc
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
        '500':
          description: server internal error

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VINIDSB580/mega_back/1.0
  - url: http://localhost:3001